name: CI

on:
  pull_request:
  workflow_call: # Make this workflow callable from other workflows
  # Deliberately not running on `push` to avoid duplicate runs. CD workflows explicitly call this workflow.

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: "10.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release
